### ISSUE TITLE
include build instructions

### ISSUE THREAD

**Issue by JBlond** [nono303/win-svn#1]
Please include how you build it :)

**Comment by nono303** [comment]
Not as simple as that with dependencies (...320 lines of batch with dirty env-var, php and bsh scripts call^^)...
for subversion itself >= 1.10 & MSVC15 (hard path & cygwin calls):
```
set ARCH=x64
python gen-make.py --release -t vcproj --with-jdk=C:\jdk8\%ARCH% --with-serf=C:\src\serf --with-sqlite=C:\httpd-sdk\src\sqlite-amalgamation-3.22 --with-apr=C:\httpd-sdk\install --with-apr-util=C:\httpd-sdk\install --with-apr-iconv=C:\httpd-sdk\install --with-apr_memcache=C:\httpd-sdk\install --with-httpd=C:\httpd-sdk\install --with-openssl=C:\httpd-sdk\install --with-zlib=C:\httpd-sdk\install --vsnet-version=2017
/usr/bin/find /cygdrive/c/httpd-sdk/src/subversion/build/win32/vcnet-vcproj/ -type f -name "*.vcxproj" -exec sed -i 's/<PropertyGroup Label="Globals">/<PropertyGroup Label="Globals"><WindowsTargetPlatformVersion>10.0.16299.0<\/WindowsTargetPlatformVersion>/g' {} \;
/usr/bin/find /cygdrive/c/httpd-sdk/src/subversion/build/win32/vcnet-vcproj/ -type f -name "*.vcxproj" -exec sed -i 's/<AdditionalDependencies>/<AdditionalDependencies>brotlidec.lib;/g' {} \;
"C:\msvc15\MSBuild\15.0\Bin\MSBuild.exe" subversion_vcnet.sln /nowarn:C4702 /nowarn:C4703 /nologo /m:8 /t:__ALL__;__JAVAHL__ /p:Configuration=Release /p:Platform=%ARCH% /p:DebugSymbols=true /p:DebugType=None
```

**Comment by JBlond** [comment]
What I wrote down a few yearts ago

https://gist.github.com/JBlond/04af060522afad7086b18251b84ccce4

with no need for cygwin.

**Comment by nono303** [comment]
Thanks @JBlond 
cygwin is just used for global replace in *.vcxproj with find & sed to match my Windows SDK version and add brotli compression support

**Comment by JBlond** [comment]
I still think it would be nice to include the build instructions in the repo. 
maybe @Jan-E could help

**Comment by nono303** [comment]
Hi @JBlond,

Here is my raw batch but not usable as it because it depend on other script and deps build...
What kind of build instructions might be useful to put in the repo in your point of view?

```
mklink /H C:\httpd-sdk\install\lib\xml.lib C:\httpd-sdk\install\lib\expat.lib
mklink /H C:\httpd-sdk\install\lib\zlib_a.pdb C:\httpd-sdk\install\lib\zlibstatic.pdb
cd /D C:\src\subversion
git reset --hard
git clean -fdx
mkdir C:\httpd-sdk\src\subversion\Release-%ARCH%
mklink /J C:\httpd-sdk\src\subversion\Release C:\httpd-sdk\src\subversion\Release-%ARCH%
rmdir /S /Q C:\httpd-sdk\src\subversion\build\win32\vcnet-vcproj
python gen-make.py --release -t vcproj --with-jdk=C:\jdk8\%ARCH% --with-serf=C:\httpd-sdk\install\include --with-sqlite=C:\httpd-sdk\src\sqlite-amalgamation --vsnet-version=2017 --with-openssl=C:\httpd-sdk\install --with-apr-util=C:\httpd-sdk\install --with-apr=C:\httpd-sdk\install --with-apr-iconv=C:\httpd-sdk\install --with-zlib=C:\httpd-sdk\install --with-apr_memcache=C:\httpd-sdk\install --with-httpd=C:\httpd-sdk\install 
	REM ;__ALL_TESTS__ 
C:\cyg64\bin\bash /cygdrive/c/httpd-sdk/modules_bat/subversion-svn.sh
if %MSVC_DEPS% == vc15 (C:\cyg64\bin\bash /cygdrive/c/httpd-sdk/modules_bat/vcxproj2vc15.sh "subversion/build/win32/vcnet-vcproj")
C:\cyg64\bin\bash /cygdrive/c/httpd-sdk/vcxproj.sh "/cygdrive/c/httpd-sdk/src/subversion/build/win32/vcnet-vcproj/" %AVXVCX%
MSBuild.exe subversion_vcnet.sln /nowarn:C4702 /nowarn:LNK4087 /nowarn:C4703 /nowarn:C4132 /nowarn:C4389 /nowarn:C4244 /nowarn:C4245 /nowarn:C4267 /nowarn:C4018 /nowarn:C4334 /nowarn:C4189 /nowarn:C4312 /nowarn:C4090 /nowarn:C4152 /nowarn:C4146 /nologo /m:8 /t:Clean;__ALL__;__JAVAHL__ /p:Configuration=Release /p:Platform=%archmsbuild%  /p:DebugSymbols=true /p:DebugType=None

for /f "tokens=*" %%G in ('dir C:\src\subversion\Release\*.exe /s/b') do (
Copy /Y %%~pG%%~nG.exe D:\github\NONO_subversion\%MSVC_DEPS%\%ARCH%%AVXB%\%%~nG.exe
Copy /Y %%~pG%%~nG.pdb D:\github\NONO_subversion\%MSVC_DEPS%\%ARCH%%AVXB%\%%~nG.pdb
)
for /f "tokens=*" %%G in ('dir C:\src\subversion\Release\*.dll /s/b') do (
Copy /Y %%~pG%%~nG.dll D:\github\NONO_subversion\%MSVC_DEPS%\%ARCH%%AVXB%\%%~nG.dll
Copy /Y %%~pG%%~nG.pdb D:\github\NONO_subversion\%MSVC_DEPS%\%ARCH%%AVXB%\%%~nG.pdb
)
for /f "tokens=*" %%G in ('dir C:\src\subversion\Release\*.so /s/b') do (
Copy /Y %%~pG%%~nG.so D:\github\NONO_subversion\%MSVC_DEPS%\%ARCH%%AVXB%\%%~nG.so
Copy /Y %%~pG%%~nG.pdb D:\github\NONO_subversion\%MSVC_DEPS%\%ARCH%%AVXB%\%%~nG.pdb
)

set DEPS=\deps\
mkdir D:\github\NONO_subversion\%MSVC_DEPS%\%ARCH%%AVXB%%DEPS%
if %ARCH% == x64 (
	set sslarch=-x64
)

Copy /Y C:\httpd-sdk\install\bin\libssl-1_1%sslarch%.dll D:\github\NONO_subversion\%MSVC_DEPS%\%ARCH%%AVXB%%DEPS%libssl-1_1%sslarch%.dll
Copy /Y C:\httpd-sdk\install\bin\libcrypto-1_1%sslarch%.dll D:\github\NONO_subversion\%MSVC_DEPS%\%ARCH%%AVXB%%DEPS%libcrypto-1_1%sslarch%.dll
Copy /Y C:\httpd-sdk\install\bin\libssl-1_1%sslarch%.pdb D:\github\NONO_subversion\%MSVC_DEPS%\%ARCH%%AVXB%%DEPS%libssl-1_1%sslarch%.pdb
Copy /Y C:\httpd-sdk\install\bin\libcrypto-1_1%sslarch%.pdb D:\github\NONO_subversion\%MSVC_DEPS%\%ARCH%%AVXB%%DEPS%libcrypto-1_1%sslarch%.pdb

Copy /Y C:\httpd-sdk\install\bin\libexpat.dll D:\github\NONO_subversion\%MSVC_DEPS%\%ARCH%%AVXB%%DEPS%libexpat.dll
Copy /Y C:\httpd-sdk\install\bin\libapr-1.dll D:\github\NONO_subversion\%MSVC_DEPS%\%ARCH%%AVXB%%DEPS%libapr-1.dll
Copy /Y C:\httpd-sdk\install\bin\libapriconv-1.dll D:\github\NONO_subversion\%MSVC_DEPS%\%ARCH%%AVXB%%DEPS%libapriconv-1.dll
Copy /Y C:\httpd-sdk\install\bin\libaprutil-1.dll D:\github\NONO_subversion\%MSVC_DEPS%\%ARCH%%AVXB%%DEPS%libaprutil-1.dll
Copy /Y C:\httpd-sdk\install\bin\brotlienc.dll D:\github\NONO_subversion\%MSVC_DEPS%\%ARCH%%AVXB%%DEPS%brotlienc.dll
Copy /Y C:\httpd-sdk\install\bin\brotlicommon.dll D:\github\NONO_subversion\%MSVC_DEPS%\%ARCH%%AVXB%%DEPS%brotlicommon.dll
Copy /Y C:\httpd-sdk\install\bin\brotlidec.dll D:\github\NONO_subversion\%MSVC_DEPS%\%ARCH%%AVXB%%DEPS%brotlidec.dll
Copy /Y C:\httpd-sdk\install\bin\libserf-2.dll D:\github\NONO_subversion\%MSVC_DEPS%\%ARCH%%AVXB%%DEPS%libserf-2.dll

Copy /Y C:\httpd-sdk\install\bin\libssl-1_1%sslarch%.pdb D:\github\NONO_subversion\%MSVC_DEPS%\%ARCH%%AVXB%%DEPS%libssl-1_1%sslarch%.pdb
Copy /Y C:\httpd-sdk\install\bin\libexpat.pdb D:\github\NONO_subversion\%MSVC_DEPS%\%ARCH%%AVXB%%DEPS%libexpat.pdb
Copy /Y C:\httpd-sdk\install\bin\libapr-1.pdb D:\github\NONO_subversion\%MSVC_DEPS%\%ARCH%%AVXB%%DEPS%libapr-1.pdb
Copy /Y C:\httpd-sdk\install\bin\libapriconv-1.pdb D:\github\NONO_subversion\%MSVC_DEPS%\%ARCH%%AVXB%%DEPS%libapriconv-1.pdb
Copy /Y C:\httpd-sdk\install\bin\libaprutil-1.pdb D:\github\NONO_subversion\%MSVC_DEPS%\%ARCH%%AVXB%%DEPS%libaprutil-1.pdb
Copy /Y C:\httpd-sdk\install\bin\libcrypto-1_1%sslarch%.pdb D:\github\NONO_subversion\%MSVC_DEPS%\%ARCH%%AVXB%%DEPS%libcrypto-1_1%sslarch%.pdb
Copy /Y C:\httpd-sdk\install\bin\brotlienc.dll D:\github\NONO_subversion\%MSVC_DEPS%\%ARCH%%AVXB%%DEPS%brotlienc.pdb
Copy /Y C:\httpd-sdk\install\bin\brotlicommon.dll D:\github\NONO_subversion\%MSVC_DEPS%\%ARCH%%AVXB%%DEPS%brotlicommon.pdb
Copy /Y C:\httpd-sdk\install\bin\brotlidec.dll D:\github\NONO_subversion\%MSVC_DEPS%\%ARCH%%AVXB%%DEPS%brotlidec.pdb
Copy /Y C:\httpd-sdk\install\bin\libserf-2.pdb D:\github\NONO_subversion\%MSVC_DEPS%\%ARCH%%AVXB%%DEPS%libserf-2.pdb
cd /D C:\httpd-sdk\modules_bat
```

**Comment by Jan-E** [comment]
The problem might be in the way you build your dependencies. If you want your repo to be compatible with an Apachelounge or Apachehaus httpd you shouldn't build Apache yourself, but extract an AL or AH build in C:\httpd-sdk\install

As an example I have used https://home.apache.org/~steffenal/VC15/binaries/httpd-2.4.41-win64-VC15.zip (downloadlink at https://www.apachelounge.com/download/VC15/ ):

python gen-make.py for svn-1.10.6 with my own dirs for OpenSSL (missing opensslv.h), zlib (missing zlib.h) and SQLite:

> C:\\>python gen-make.py --release -t vcproj --vsnet-version=2017 --with-apr-util=C:\httpd-sdk\install --with-apr=C:\httpd-sdk\install --with-apr-iconv=C:\httpd-sdk\install --with-apr_memcache=C:\httpd-sdk\install --with-httpd=C:\httpd-sdk\install --with-openssl=\php-sdk\win64build.vc15 --with-zlib=\php-sdk\win64build.vc15 --with-sqlite=..\sqlite
> 
> Generating for Visual Studio 2017
> 
> Could not find installed SWIG
> Found apr 1.7.0
> Found apr-util 1.6.1
> Found apr_memcache 1.6.1
> Found expat 2.2.7
> Found httpd 2.4.41
> Found mod_dav 2.4.41
> Found openssl 1.1.1d
> Found sqlite 3.24.0
> Found zlib 1.2.11
> Using bundled lz4 1.7.5
> Using bundled utf8proc 2.1.0
> swig not found; skipping SWIG file generation...

**Comment by JBlond** [comment]
Awesome! 
Putting the script into the repo might others help to build mod_svn themselves. The build instructions for windows almost don't exist. I've seen too many windows builds for windows die, because nobody knew how to do it after the original maintainer gave up for some reason.

**Comment by Jan-E** [comment]
In my own svn-builds I do not use an AL or AH download, but am using my own builds (for VC9, VC11, VC14, VC14 with OpenSSL 1.1.1, VC15 and VS16). Example for VC15 x64:

> Generating for Visual Studio 2017
> 
> Could not find installed SWIG
> Found apr 1.7.0
> Found apr-util 1.6.1
> Found apr_memcache 1.6.1
> Found expat 2.2.9
> Found httpd 2.4.43
> Found mod_dav 2.4.43
> Found openssl 1.1.1d
> Found sasl 2.1.27
> Found serf 1.3.9
> Found sqlite 3.24.0
> Found zlib 1.2.11
> Using bundled lz4 1.7.5
> Using bundled utf8proc 2.1.0
> swig not found; skipping SWIG file generation...

But by far the easiest way is to use an AL or AH download. Probably adding opensslv.h and zlib.h to C:\httpd-sdk\install\include is enough for detecting OpenSSL and Zlib as well. Then you only have to add SQLite to build svn-1.10.6. Downloads are here:

https://windows.php.net/downloads/php-sdk/deps/
For instance: https://windows.php.net/downloads/php-sdk/deps/vc15/x64/sqlite3-3.31.1-vc15-x64.zip

**Comment by Jan-E** [comment]
BTW: This will change this evening in OpenSSL 1.1.1f
And I see I can update SQLite for VC15 from 3.24.0 to 3.31.1 (which the php-devs use).

The Python version I am using is Python 2.7.8

**Comment by nono303** [comment]
Ok Ok !
As I am stuck up in NZ for 2 weeks before might flighting back to France (Thanks Covid ^^), I'll drop all my "dirty" scripts for httpd, svn & all deps in a new repo tomorrow.
Note that **they are actually not directly usable** as far as they are not fully contextualized to ENV & installs.
But in this way, I & U might contextualize, enhance and have an external view of my way of building them ;)

**Comment by ahwm** [comment]
I'd be interested in seeing this, too. I struggled with building SVN myself for a while before giving up (and eventually finding this repository for binary downloads, so thank you for that!).

**Comment by Jan-E** [comment]
> Awesome!
> Putting the script into the repo might others help to build mod_svn themselves. The build instructions for windows almost don't exist. I've seen too many windows builds for windows die, because nobody knew how to do it after the original maintainer gave up for some reason.

Better yet: build it online, using Appveyor, The build log is here:
https://ci.appveyor.com/project/Jan-E/svn-windows/builds/31890527?fullLog=true#L350

The tests ends in the same results as when I build it locally
https://ci.appveyor.com/project/Jan-E/svn-windows/builds/31890527?fullLog=true#L4386
Tiny difference: online has one more total tests and 1 more skipped tests.

I am building this version against the latest AL download:
https://github.com/Jan-E/svn-windows/blob/master/appveyor.yml#L26

Appveyor's VS2019 OS is still using OpenSSL 1.1.1e, so that is the version I am using for building svn-1.10.6-x64.

The next run will create a downloadable artifact, I hope. But every run takes almost an hour so it will take some time before I am sure about this.

**Comment by Jan-E** [comment]
See https://ci.appveyor.com/project/Jan-E/svn-windows/builds/31893989/artifacts for a complete svn-1.10.6-x64.zip (built with VS16).

The complete buildlog is here:
https://ci.appveyor.com/project/Jan-E/svn-windows/builds/31893989?fullLog=true

**Comment by nono303** [comment]
Hi,
Have a look at https://github.com/nono303/win-build-scripts
just updated win-svn readme with the link.
Closing this issue and we may continue to exchange on win-build-scripts ;)

**Comment by nono303** [comment]
Hi @Jan-E @JBlond @ahwm,
I Just released a cleaned version of my build scripts on https://github.com/nono303/win-build-scripts/tree/1.0.0
Don't hesitate to give me some feedback ;)

**Comment by JBlond** [comment]
@nono303 awesome! Looks good! I hope you are back from NZ

**Comment by nono303** [comment]
> @nono303 awesome! Looks good! I hope you are back from NZ
Flying back from NZ was quite hard to organize but finally, I came back to France nicely (...and had great hike time during NZ lock-down ;)
