### ISSUE TITLE
build with SSL 1.1.1A

### ISSUE THREAD

**Issue by vlabella** [nono303/win-svn#2]
SVN crashes when running under latest apache that is built against ssl 1.1.1a from apache lounge. I believe the crash is because SVN is built with 1.1.1.  Could you rebuild using SSL 1.1.1a?

**Comment by nono303** [comment]
hi @vlabella ,
I just released 1.11.1 with SSL 1.1.1a (see @tag 1.11.1)
Could you test it and give me a feedback ?

**Comment by vlabella** [comment]
Yes! Apache 2.4.38 VC15 x64 from apache lounge starts now.  All my svn clients connect fine and use NTLM auth.  However, when I use the svn.exe in the mod_svn package to connect to the repo it continually asks for the password.  The error log says
[Tue Jan 22 12:02:56.248317 2019] [auth_ntlm:error] [pid 3000:tid 2684] [client ********] client used wrong authentication scheme: (null) for /svn/*****/****** (needed NTLM)

I installed tortoiseSVN on the server and that build connected and authenticated fine.  I did not have this problem on any of your other builds.  Does NTLM auth need to be enabled in the build somehow or is it a config problem?  Seems to be only when svn.exe is connecting as a client since all other computers can authenticate fine just not the server.  I am running on win server 2016 .

Thanks!!

**Comment by nono303** [comment]
Hi @vlabella ,
Good news if it works fine for you ^^
Concerning your NTLM auth issue with svn.exe, I'm pretty sure that’s it's not linked to build config: 

- I Never changed my build config chain in svn 1.X
- I Never saw build config option related to auth of NTLM
- My httpd deps build used for svn release contain all auth method module enabled

So, maybe have a look on http://svnbook.red-bean.com/en/1.8/svn.serverconfig.netmodel.html#svn.serverconfig.netmodel.creds but can't say more on it!
