### ISSUE TITLE
mod_dav_svn.so not for windows

### ISSUE THREAD

**Issue by Michel4OpenOpcUa** [nono303/win-svn#7]
Hello,
After MOD_DAV_SVN.SO failed to be loaded. 
I tried to validate the 64bits version dependencies with depends. 
The tool report :
No DOS or PE signature found. This file is not a valid 32-bit or 64-bit Windows module.

Any idea ?
Regards
Michel

**Comment by Jan-E** [comment]
Could you try the ones in the modules folder at 
https://ci.appveyor.com/project/Jan-E/svn-windows/builds/33232754/job/juthm7sefil8tx52/artifacts (x64)
https://ci.appveyor.com/project/Jan-E/svn-windows/builds/33232754/job/2bj3hkrld7y91k2q/artifacts (x86)

**Comment by Michel4OpenOpcUa** [comment]
Hello,
Thank you for those links. The 64bit version is working with httpd 2.4.43 vs16.
regards
Michel

**Comment by Jan-E** [comment]
They should work with the ApacheLounge httpd's, because I am building SVN using a download from ApacheLounge. See the build log: https://ci.appveyor.com/project/Jan-E/svn-windows/builds/33232754/job/juthm7sefil8tx52
