### ISSUE TITLE
Server Restart with unknown status 3228369022 

### ISSUE THREAD

**Issue by AntonWert** [nono303/win-svn#8]
Hello,
I used the latest x64 (VC16) binaries from apachelounge with php 8.1 and all works well, no warning or missing dependencies.
When I include the VC16 binaries I get the following error in error.log of apache accessing with Tortoise SVN, restarting the server in a loop, see below.
TortoiseSVN gives up after about 2 minutes with the information:
Unable to connect to a reprository att URL.
http://xxxx/svn/xxx
Error running context: The connection was closed by remote host.

Error log from apache:

[Thu Jan 13 07:26:37.726690 2022] [mpm_winnt:notice] [pid 2680:tid 376] AH00354: Child: Starting 64 worker threads.
[Thu Jan 13 07:26:39.881752 2022] [mpm_winnt:notice] [pid 1436:tid 712] AH00428: Parent: child process 2680 exited with status 3228369022 -- Restarting.
[Thu Jan 13 07:26:39.928630 2022] [mpm_winnt:notice] [pid 1436:tid 712] AH00455: Apache/2.4.52 (Win64) SVN/1.14.1 PHP/8.1.1 configured -- resuming normal operations
[Thu Jan 13 07:26:39.928630 2022] [mpm_winnt:notice] [pid 1436:tid 712] AH00456: Apache Lounge VS16 Server built: Dec 17 2021 10:17:38

Configuration worked stratight forward using the f-w method. Reprositories have been copied from an older (working) version based on x32

What might be the issue?
What does the status 3228369022  tell?

Can I provide any helpful information?

**Comment by nono303** [comment]
Hi @AntonWert ,
status `3228369022` == `C06D007E` in hex
 - https://stackoverflow.com/questions/9383722/missing-external-function-in-ieframe-dll-and-shlwapi-dll-when-referencing-sharps : might be a bad dll dependencies call related to your path
1) check dll dependencies tree with [Dependencies](https://github.com/lucasg/Dependencies/releases) 
2) if you don't find anything, attach httpd with [ProcDump](https://docs.microsoft.com/en-us/sysinternals/downloads/procdump) to create a coredump of this exception that can be investigated with [windbg](https://www.microsoft.com/en-us/p/windbg-preview/9pgjgd53tn86?activetab=pivot:overviewtab)
> Configuration worked stratight forward using the f-w method. Reprositories have been copied from an older (working) version based on x32

Don't understand this: how an older **x32** based version can work with **x64** httpd?

**Comment by AntonWert** [comment]
Hello @nono303 ,
thank you for the clarification. And thank you for your help.  Just to answer your question at first: my old and running instalation was based on 32 bit versions of Apache PHP and SVN. No I want to do the update to a state of the art 64 bit installation.

I checked step 1 with Dependencies. For boh modules (mod_dav_svn.so and mod_authz_svn.so) it is happy finding all referenced dlls.
I will investigate how to go ahead with ProcDump and windbg.

**Comment by AntonWert** [comment]
Hello @nono303 ,
sorry for askin agin, but maybe you have an hint for me how to atteach ProcDump to the correct task. I tried it with 
`procdump64.exe -e -f 3228369022 [PID]` for the httpd, but it did not catch any issue. Maybe because it is one of the worker threads?
`procdump64.exe -e -f 3228369022 httpd` does not start due to multiple processes with the same name.

**Comment by Jan-E** [comment]
A possible other way: use the binaries in
https://ci.appveyor.com/project/Jan-E/svn-windows/builds/42152590/job/rij677m90y54gi3u/artifacts
These binaries were built directly against https://www.apachelounge.com/download/VS16/binaries/httpd-2.4.52-win64-VS16.zip as you can see in the job log.
https://ci.appveyor.com/project/Jan-E/svn-windows/builds/42152590/job/rij677m90y54gi3u?fullLog=true shows you the test results at the very end. The Xfails ae Expected failures. The 2 Fails are not expected by the SVN project, but I am always getting them. They do not seem very important.

**Comment by Jan-E** [comment]
BTW: make sure that the binaries in the root dir of PHP 8.1.1 are exactly the same as those in the bin directory of Apache (for as far as binaries with the same name are in both directories).

**Comment by nono303** [comment]
> Hello @nono303 , sorry for askin agin, but maybe you have an hint for me how to atteach ProcDump to the correct task. I tried it with `procdump64.exe -e -f 3228369022 [PID]` for the httpd, but it did not catch any issue. Maybe because it is one of the worker threads? `procdump64.exe -e -f 3228369022 httpd` does not start due to multiple processes with the same name.

You can have a look here : https://docs.microsoft.com/en-us/windows-hardware/drivers/debugger/enabling-postmortem-debugging

**Comment by AntonWert** [comment]
> BTW: make sure that the binaries in the root dir of PHP 8.1.1 are exactly the same as those in the bin directory of Apache (for as far as binaries with the same name are in both directories).



> A possible other way: use the binaries in https://ci.appveyor.com/project/Jan-E/svn-windows/builds/42152590/job/rij677m90y54gi3u/artifacts These binaries were built directly against https://www.apachelounge.com/download/VS16/binaries/httpd-2.4.52-win64-VS16.zip as you can see in the job log. https://ci.appveyor.com/project/Jan-E/svn-windows/builds/42152590/job/rij677m90y54gi3u?fullLog=true shows you the test results at the very end. The Xfails ae Expected failures. The 2 Fails are not expected by the SVN project, but I am always getting them. They do not seem very important.

These binarys seem to be unsave, see:
https://www.virustotal.com/gui/file/b639840b2bef0f59981d5a6de7af1dc973ebe9f4caa83e32ff38e4f8a5e71bfc?nocache=1

**Comment by Jan-E** [comment]
On my development machine with the libsvn_*.dll's in https://ci.appveyor.com/project/Jan-E/svn-windows/builds/42152590/job/rij677m90y54gi3u/artifacts copied to the bin direactory of Apache and the  *.so files copied to the modules directory:
```
[Thu Jan 13 12:13:02.454891 2022] [mpm_winnt:notice] [pid 7568:tid 776] AH00455: Apache/2.4.52 (Win64) mod_fcgid/2.3.10 SVN/1.14.1 OpenSSL/1.1.1m PHP/8.1.2RC1 configured -- resuming normal operations
[Thu Jan 13 12:13:02.454891 2022] [mpm_winnt:notice] [pid 7568:tid 776] AH00456: Server built: Dec 20 2021 01:56:45
[Thu Jan 13 12:13:02.454891 2022] [core:notice] [pid 7568:tid 776] AH00094: Command line: 'N:\\phpdev\\Apache24.16x64\\bin\\httpd.exe -d N:/phpdev/Apache24.16x64'
[Thu Jan 13 12:13:02.474873 2022] [mpm_winnt:notice] [pid 7568:tid 776] AH00418: Parent: Created child process 12092
[Thu Jan 13 12:13:03.147249 2022] [mpm_winnt:notice] [pid 12092:tid 1220] AH00354: Child: Starting 64 worker threads.
```
No other directories involved. No path settings used.
Apache/2.4.52 (Win64) mod_fcgid/2.3.10 SVN/1.14.1 OpenSSL/1.1.1m PHP/8.1.2RC1 running fine.

**Comment by AntonWert** [comment]
> BTW: make sure that the binaries in the root dir of PHP 8.1.1 are exactly the same as those in the bin directory of Apache (for as far as binaries with the same name are in both directories).

Do you mean replacing the EXE's in the PHP-dir with those from the apache/bin dir? (or vise versa?)

**Comment by AntonWert** [comment]
> On my development machine with the libsvn_*.dll's in https://ci.appveyor.com/project/Jan-E/svn-windows/builds/42152590/job/rij677m90y54gi3u/artifacts copied to the bin direactory of Apache and the *.so files copied to the modules directory:
> 
> ```
> [Thu Jan 13 12:13:02.454891 2022] [mpm_winnt:notice] [pid 7568:tid 776] AH00455: Apache/2.4.52 (Win64) mod_fcgid/2.3.10 SVN/1.14.1 OpenSSL/1.1.1m PHP/8.1.2RC1 configured -- resuming normal operations
> [Thu Jan 13 12:13:02.454891 2022] [mpm_winnt:notice] [pid 7568:tid 776] AH00456: Server built: Dec 20 2021 01:56:45
> [Thu Jan 13 12:13:02.454891 2022] [core:notice] [pid 7568:tid 776] AH00094: Command line: 'N:\\phpdev\\Apache24.16x64\\bin\\httpd.exe -d N:/phpdev/Apache24.16x64'
> [Thu Jan 13 12:13:02.474873 2022] [mpm_winnt:notice] [pid 7568:tid 776] AH00418: Parent: Created child process 12092
> [Thu Jan 13 12:13:03.147249 2022] [mpm_winnt:notice] [pid 12092:tid 1220] AH00354: Child: Starting 64 worker threads.
> ```
> 
> No other directories involved. No path settings used. Apache/2.4.52 (Win64) mod_fcgid/2.3.10 SVN/1.14.1 OpenSSL/1.1.1m PHP/8.1.2RC1 running fine.

I do have a simmelar result. Apache is starting up fine. Also PHP seems to work well. But wen I use a SVN client to access a resprository, I get the crash, listed above.

**Comment by Jan-E** [comment]
> These binarys seem to be unsave, see:
https://www.virustotal.com/gui/file/b639840b2bef0f59981d5a6de7af1dc973ebe9f4caa83e32ff38e4f8a5e71bfc?nocache=1

Most likely that some of the files used for the SVN tests do things that seem malicious. With only the SVN dll's, libs and so's: https://www.virustotal.com/gui/file/4d4a100445e21baa0ee6dd9b858e5e5d308480724f57cb9b16a7a71679d11685?nocache=1
See https://phpdev.toolsforresearch.com/svn-1.14.1-vs16-x64.zip

**Comment by Jan-E** [comment]
> I do have a simmelar result. Apache is starting up fine. Also PHP seems to work well. But wen I use a SVN client to access a resprository, I get the crash, listed above.

Can you share the commands you are using, so I can try to replicate it?

**Comment by AntonWert** [comment]
> > These binarys seem to be unsave, see:
> > https://www.virustotal.com/gui/file/b639840b2bef0f59981d5a6de7af1dc973ebe9f4caa83e32ff38e4f8a5e71bfc?nocache=1
> 
> Most likely that some of the files used for the SVN tests do things that seem malicious. With only the SVN dll's, libs and so's: https://www.virustotal.com/gui/file/4d4a100445e21baa0ee6dd9b858e5e5d308480724f57cb9b16a7a71679d11685?nocache=1 See https://phpdev.toolsforresearch.com/svn-1.14.1-vs16-x64.zip

That looks better, I will have a try on these built

**Comment by AntonWert** [comment]
> > I do have a simmelar result. Apache is starting up fine. Also PHP seems to work well. But wen I use a SVN client to access a resprository, I get the crash, listed above.
> 
> Can you share the commands you are using, so I can try to replicate it?

I do have the old reproitory on the server (see therefore my minitial posts) and I use "SVN checkout" to make a local copy. I use the GUI from Tortoise SVN, but with  command line it is the same

**Comment by AntonWert** [comment]
> > I do have a simmelar result. Apache is starting up fine. Also PHP seems to work well. But wen I use a SVN client to access a resprository, I get the crash, listed above.
> 
> Can you share the commands you are using, so I can try to replicate it?

So, I used your files for the test @Jan-E . I checked with the dependency tool, and nothing seemed to be missing.

**This is the SVN part of the Apache config:**
<Location /svn/test/>
DAV svn
SVNListParentPath off
SVNParentPath "E:\data\svn\repos\test"
SVNIndexXSLT "/svnindex.xsl"
AuthType Basic
AuthName "server"
AuthUserFile "E:\programme\Apache2464\passwd"
AuthzSVNAccessFile "E:\programme\Apache2464\svnaccessfile"
Require valid-user
</Location>

**This the error.log:**
[Thu Jan 13 14:52:38.720133 2022] [mpm_winnt:notice] [pid 9768:tid 392] AH00455: Apache/2.4.52 (Win64) SVN/1.14.1 PHP/8.1.1 configured -- resuming normal operations
[Thu Jan 13 14:52:38.720133 2022] [mpm_winnt:notice] [pid 9768:tid 392] AH00456: Apache Lounge VS16 Server built: Dec 17 2021 10:17:38
[Thu Jan 13 14:52:38.720133 2022] [core:notice] [pid 9768:tid 392] AH00094: Command line: 'httpd -d E:/programme/Apache2464'
[Thu Jan 13 14:52:38.741852 2022] [mpm_winnt:notice] [pid 9768:tid 392] AH00418: Parent: Created child process 10468
[Thu Jan 13 14:52:39.288931 2022] [mpm_winnt:notice] [pid 10468:tid 4] AH00354: Child: Starting 64 worker threads.
[Thu Jan 13 14:54:01.056434 2022] [auth_basic:error] [pid 10468:tid 1244] [client 10.253.104.16:51645] AH01618: user test not found: /svn/test/test_training
[Thu Jan 13 14:54:18.853307 2022] [mpm_winnt:notice] [pid 9768:tid 392] AH00428: Parent: child process 10468 exited with status 3228369022 -- Restarting.
[Thu Jan 13 14:54:18.884562 2022] [mpm_winnt:notice] [pid 9768:tid 392] AH00455: Apache/2.4.52 (Win64) SVN/1.14.1 PHP/8.1.1 configured -- resuming normal operations
[Thu Jan 13 14:54:18.884562 2022] [mpm_winnt:notice] [pid 9768:tid 392] AH00456: Apache Lounge VS16 Server built: Dec 17 2021 10:17:38
[Thu Jan 13 14:54:18.884562 2022] [core:notice] [pid 9768:tid 392] AH00094: Command line: 'httpd -d E:/programme/Apache2464'
[Thu Jan 13 14:54:18.884562 2022] [mpm_winnt:notice] [pid 9768:tid 392] AH00418: Parent: Created child process 9120
[Thu Jan 13 14:54:19.431483 2022] [mpm_winnt:notice] [pid 9120:tid 780] AH00354: Child: Starting 64 worker threads.


And here the client SVN checkout-try:
**C:\Users\test\test>svn checkout http://server:8080/svn/test/test_training
Authentication realm: <http://server:8080> server
Password for 'test': *******
Authentication realm: <http://server:8080> server
Username: test
Password for 'test': *******
svn: E170013: Unable to connect to a repository at URL 'http://server:8080/svn/test/test_training'
svn: E730054: Error running context: Eine vorhandene Verbindung wurde vom Remotehost geschlossen.**

And yes, I had to configure apache to port 8080 because 80 is currently occupied

**Comment by Jan-E** [comment]
Could you try it with just
```
<Location /svn/test/>
DAV svn
SVNListParentPath on
SVNParentPath "E:\data\svn\repos\test"
</Location>
```
That worked on my dev laptop.

**Comment by Jan-E** [comment]
> AH01618: user test not found: /svn/test/test_training

When did this happen? Is there a line for user 'test' in E:\programme\Apache2464\passwd?

**Comment by AntonWert** [comment]
> > AH01618: user test not found: /svn/test/test_training
> 
> When did this happen? Is there a line for user 'test' in E:\programme\Apache2464\passwd?

I do not know why the svn client asked two times for the credentials, I think the first one was rejected.
I double checked this behaviour and the log message is already present when the 2nd credentials are requested (but not typed in)

---------------------------------------------------------

When I wanted to check the proposel with the reduced httpd.conf I found a working solution:

It depends on the **order** of the path variables.

In all of my tests I had added the apache/bin and apache/modules to the path.
When I list the path, they were set in this order:

1. apache/module
2. apache/bin
3. %systemroot% .....

**I can confirm that the order must be:
1. %systemroot% .....
2. apache/bin
3. apache/module**

also 
1. %systemroot% .....
2. apache/module
3. apache/bin
seems not to work.


Just for sumarize the working combination:
Apache/2.4.52 (Win64)  from apachelounge
SVN/1.14.1 provided in this thread by Jan-E
PHP/8.1.1 from php.net (x64 thread save)


I do not know why, but this solves the problem for me.
I will close the issue here, but if it helps, I could answer or make tests. Just ask. And thank you for your support.

**Comment by nono303** [comment]
Thx @AntonWert for these tests!
Could you just have a try with "my" SVN version with the working path order please and see what happen?

**Comment by Jan-E** [comment]
apache/modules should not have to be in your path. I was surprised by the advice that @nono303 gives in https://github.com/nono303/win-svn#f-w-method to copy dll’s to the modules dir. Could you check if there are any dll’s from previous tests left behind in that dir? I guess that must be the case, because the 2 failing path configs have apache/modules before apache/bin
Remove those dll’s there and remove apache/modules from your path.

And as a BTW: apache/bin is not really needed in your path either. On my dev laptop there are 12 apache instances (VC9, VC11, VC14+OpenSSL 1.0.2, VC14+OpenSSL 1.1.1, VC15, VS16, all x64 and x86), which I can start without any changes in the path settings. No apache dirs are in my path.

**Comment by nono303** [comment]
> I was surprised by the advice that @nono303 gives in https://github.com/nono303/win-svn#f-w-method 

as the tile `f-w-method` said, this is @f-w method ;)
my method https://github.com/nono303/win-svn#nono303-method is to put specific mod_svn dll deps to a separate folder to be `easier to upgrade & httpd independent`
it was already debated here https://github.com/nono303/win-svn/pull/4

**Comment by AntonWert** [comment]
My installation is clean, just the unzipped packages from apachelounge and so on. I can rule out any left over.
I found a dependency-link to libhttpd.dll witch could be the case for the needed apache/bin path - I don't know.

And I just tried again with your advice nono303 (and your files) in a separate folder (and having a path link to that).


It works not with
%systemroot% .....
apache/bin
apache/svn-files-from-nono
apache/module

nor with
%systemroot% .....
apache/svn-files-from-nono
apache/bin
apache/module

**Comment by Jan-E** [comment]
Putting dll’s in different dirs is asking for conflicts. I guess there are conflicting dll’s in apache/modules and apache/bin right now, which made 2 of the 3 path configs fail. Put things where they belong in a basic httpd.conf: so-files in the modules dir and libsvn_*.dll files in the bin dir.

**Comment by Jan-E** [comment]
> I found a dependency-link to libhttpd.dll witch could be the case for the needed apache/bin path - I don't know.

If you want to run something like the dependency walker on so-files it might be needed to add the bin dir of apache to the path. But for normal operations of Apache that is not strictly needed.
